version: 0.2

env:
  variables:
     docker_image_branch: F#SRC-3404_docker_release_on_AWS
     release_tag_flavour: kinetic
     release_tag_version: 1.0.28
  parameter-store:
     GITHUB_LOGIN : GITHUB_LOGIN
     GITHUB_PASSWORD : GITHUB_PASSWORD
     DOCKER_HUB_USERNAME: DOCKER_HUB_USERNAME
     DOCKER_HUB_PASSWORD: DOCKER_HUB_PASSWORD
     id_rsa: id_rsa
phases:
  install:
    runtime-versions:
      docker: 18
  build:
    commands:
      - chown -R $MY_USERNAME:$MY_USERNAME $CODEBUILD_SRC_DIR
      - git checkout $docker_image_branch
      - echo "Setting up the nginx server"
      - echo $id_rsa >> ./id_rsa
      - docker run --name=nginx-ssh -d -v $CODEBUILD_SRC_DIR:/usr/share/nginx/html -p 8008:80 nginx
      - cd $(find . -name system-test)
      - ./check-tag.sh -f $release_tag_flavour -v $release_tag_version
      - ./system-test.sh
  post_build:
    commands:
      - echo "Killing nginx server..."
      - docker stop nginx-ssh && docker rm nginx-ssh
      - echo "Removing ssh key ..."
      - cd $CODEBUILD_SRC_DIR && rm -f id_rsa
